Repository sunlabuiuc/PyHealth, pull requests merged in 2025-05, with the labels that each got.

#368 Fix issues with `BaseDataset.load_table()`
  pyhealth/datasets/base_dataset.py
  pyhealth/datasets/configs/mimic3.yaml
  pyhealth/datasets/mimic3.py
  pyhealth/tasks/mortality_prediction.py
Labels: bug

#374 Doc Updates to about.rst, index.rst, and tutorials.rst
  docs/about.rst
  docs/index.rst
  docs/tutorials.rst
Labels: documentation

#378 2-3× Speedup for `BaseDataset.set_task()`
  pyhealth/data/data.py
  pyhealth/datasets/base_dataset.py
  pyhealth/datasets/mimic4.py
  pyhealth/tasks/in_hospital_mortality_mimic4.py
  pyhealth/tasks/readmission_30days_mimic4.py
Labels: core, infra
